name: ServerDeploy

on:
  push:
    branches:
      - main
jobs:
  deploy_job:
    runs-on: ubuntu-latest #运行环境
    name: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm i pnpm -g
      - run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm docs:build

      # 利用action把build好的文件上传到服务器/xxx路径下,需要确认此目录已在服务端创建
      - name: deploy file to server
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: 'ubuntu' #ssh user name
          server: '${{ secrets.SERVER_IP }}' #引用之前创建好的secret
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} #引用之前创建好的secret
          local_path: 'docs/.vitepress/GRIT' # 对应我们项目build的文件夹路径
          remote_path: '/home/ubuntu/docker/data/blog_back/nginx/html/GRIT'
