name: deploying Hexo project to GitHub pages
on:
  push:
    branches:
      - main # main 分支有 push 行为时就触发这个 action

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm i pnpm -g
      - run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm docs:build

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} #引用之前创建好的secret
          ARGS: -rltgoDzvO --delete
          SOURCE: docs/.vitepress/GRIT # 对应我们项目build的文件夹路径
          REMOTE_HOST: ${{ secrets.SERVER_IP }} #ip或域名
          REMOTE_USER: ubuntu #ssh user name
          TARGET: /home/ubuntu/docker/data/blog_back/nginx/html/GRIT
          EXCLUDE:
